#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Patch k8s_agent.py on the authoritative build host.
# Fix1: _build_base_server_url reads server.iP (config.yaml uses iP key, not ip)
# Fix2: report_k8s_result sends top-level id/success/message (backend reads top-level)
import io
import sys

PATH = '/home/bontor/agent-build/Agent-master/core/k8s_agent.py'

with io.open(PATH, 'r', encoding='utf-8') as f:
    src = f.read()

orig_len = len(src)
changed = []

# ---- Fix1: iP-compatible server ip read ----
old1 = '''    cfg = load_config()

    server_ip = cfg.get(
        "server",
        {}
    ).get(
        "ip",
        "127.0.0.1"
    )

    port = cfg.get(
        "server",
        {}
    ).get(
        "port",
        30000
    )

    if not server_ip.startswith(("http://", "https://")):
        server_ip = f"http://{server_ip}"

    return f"{server_ip}:{port}"'''
new1 = '''    cfg = load_config()

    server_cfg = cfg.get("server", {}) or {}

    # config.yaml generated by backend uses key "iP" (not "ip").
    # Fall back across case variants to avoid reporting to 127.0.0.1.
    server_ip = (
        server_cfg.get("iP")
        or server_cfg.get("ip")
        or server_cfg.get("Ip")
        or "127.0.0.1"
    )

    port = server_cfg.get("port", 30000)

    if not server_ip.startswith(("http://", "https://")):
        server_ip = f"http://{server_ip}"

    return f"{server_ip}:{port}"'''
if old1 in src:
    src = src.replace(old1, new1)
    changed.append('fix1: base_server_url iP')
else:
    changed.append('fix1: NOT FOUND (check whitespace)')

# ---- Fix2: top-level report payload ----
old2 = '''        payload = {
            "map": {
                "id": task.get("id"),
                "success": success,
                "message": message
            }
        }

        response = requests.post('''
new2 = '''        payload = {
            "id": task.get("id"),
            "success": bool(success),
            "message": str(message)
        }

        response = requests.post('''
if old2 in src:
    src = src.replace(old2, new2)
    changed.append('fix2: top-level report payload')
else:
    changed.append('fix2: NOT FOUND (check whitespace)')

with io.open(PATH, 'w', encoding='utf-8') as f:
    f.write(src)

print('changed size %d -> %d' % (orig_len, len(src)))
for c in changed:
    print('  [%s]' % c)

# syntax check
import py_compile
py_compile.compile(PATH, doraise=True)
print('py_compile OK')
